export const fonts: Array<string> = [
    'Abel',
    'Abril Fatface', 
    'Alegreya',
    'Alfa Slab One',
    'ALGERIAN',
    'Allerta Stencil',
    'Amatic SC',
    'Amita',
    'Anonymous Pro',
    'Anton',
    'Architects Daughter',
    'Arial',
    'Arima Madurai',
    'Arizonia',
    'Averia Serif Libre',
    'Bad Script',
    'Bahianita',
    'BEBAS NEUE',
    'Bellota',
    'Berkshire Swash',
    'Bigelow Rules',
    'Boogaloo',
    'Bowlby One',
    'Brush Script MT',
    'BUNGEE',
    'BUNGEE SHADE',
    'BUTCHERMAN',
    'Butterfly Kids',
    'Cabin',
    'Cairo',
    'Calibri',
    'Calisto MT',
    'Cambria',
    'Candal',
    'Caveat',
    'Chango',
    'Charmonman',
    'Chewy',
    'Chilanka',
    'Chiller',
    'CINZEL',
    'CINZEL DECORATIVE',
    'Coiny',
    'Colonna MT',
    'Comfortaa',
    'Comic Sans MS',
    'Concert One',
    'Cookie',
    'Cormorant Unicase',
    'Courier New',
    'CREEPSTER',
    'Croissant One',
    'Cutive Mono',
    'Dancing Script',
    'Darker Grotesque',
    'Didact Gothic',
    'Domine',
    'Dosis',
    'Economica',
    'Eczar',
    'Elsie Swash Caps',
    'Emblema One',
    'Englebert',
    'Euphoria Script',
    'Exo',
    'Exo 2',
    'Fahkwang',
    'Fjalla One',
    'Franklin Gothic',
    'Fredericka the Great',
    'Fredoka One',
    'Fugaz One',
    'Galada',
    'Garamond',
    'Georgia',
    'Gill Sans MT',
    'Gothic Ultra',
    'Goudy Old Style',
    'Graduate',
    'Grand Hotel',
    'Gravitas One',
    'Gruppo',
    'Handlee',
    'Harrington',
    'Heebo',
    'Helvetica',
    'Hind',
    'Homemade Apple',
    'Impact',
    'Indie Flower',
    'Jokerman',
    'Josefin Sans',
    'Josefin Slab',
    'JULIUS SANS ONE',
    'Jura',
    'Just Another Hand',
    'Just Me Again Down Here',
    'Kalam',
    'Kameron',
    'Karla',
    'Khand',
    'Krona One',
    'La Belle Aurore',
    'Lato',
    'Lexend Exa',
    'Libre Baskerville',
    'Life Savers',
    'Lily Script One',
    'Limelight',
    'Lobster',
    'Lobster Two',
    'Londrina Outline',
    'Londrina Solid',
    'Lora',
    'Lucida Sans',
    'LUCKIEST GUY',
    'Maiden Orange',
    'Marvel',
    'Medula One',
    'MEGRIM',
    'MONOTON',
    'Montserrat',
    'Montserrat Alternates',
    'Mountains of Christmas',
    'Mulish',
    'Nixie One',
    'Nothing You Could Do',
    'Nova Cut',
    'Numans',
    'Nunito',
    'Old Standard TT',
    'Oleo Script',
    'Open Sans',
    'Open Sans Condensed',
    'Oranienbaum',
    'Orbitron',
    'Oswald',
    'Overlock',
    'Oxygen',
    'Papyrus',
    'Passion One',
    'Pathway Gothic One',
    'Pavanam',
    'Paytone One',
    'Permanent Marker',
    'Petit Formal Script',
    'Playball',
    'Playfair Display',
    'Poller One',
    'Poppins',
    'Prata',
    'Quattrocento',
    'Questrial',
    'Quicksand',
    'Racing Sans One',
    'Raleway',
    'Rammetto One',
    'Ravi Prakash',
    'Red Hat Display',
    'Righteous',
    'Roboto',
    'Roboto Mono',
    'Roboto Slab',
    'Rock Salt',
    'Rokkitt',
    'RUBIK MONO ONE',
    'Shadows Into Light',
    'Shrikhand',
    'SIGMAR ONE',
    'Slabo 27px',
    'Slackey',
    'Smokum',
    'Sofia',
    'Source Code Pro',
    'Spicy Rice',
    'Stint Ultra Expanded',
    'SYNCOPATE',
    'Tahoma',
    'Teko',
    'Tenor Sans',
    'Times New Roman',
    'Trebuchet MS',
    'Ubuntu',
    'Ultra',
    'Underdog',
    'unica one',
    'Varela',
    'Varela Round',
    'Vast Shadow',
    'Verdana',
    'Vidaloka',
    'Vollkorn',
    'Wide Latin',
    'Wire One',
    'Work Sans',
    'Yantramanav',
    'Yatra One',
    'Yellowtail',
]