export const fonts: Array<string> = [
    'Abel',
    'Abril Fatface',
    'Agency FB',
    'Alegreya',
    'Alfa Slab One',
    'ALGERIAN',
    'Allerta Stencil',
    'Amatic SC',
    'Amble',
    'Amita',
    'Annie Use Yor Telescope',
    'Anonymous Pro',
    'Anton',
    'Architects Daughter',
    'Arial',
    'Arima Madurai',
    'Arizonia',
    'Averia Serif Libre',
    'Bad Script',
    'Bahianita',
    'Bear and Loupe',
    'BEBAS NEUE',
    'Bellota',
    'Berkshire Swash',
    'Beth Eller',
    'Big Snow',
    'Bigelow Rules',
    'Biorhyme Expanded',
    'Boogaloo',
    'Bowlby One',
    'Brush Script MT',
    'BUNGEE',
    'BUNGEE SHADE',
    'BUTCHERMAN',
    'Butterfly Kids',
    'Cabin',
    'Cairo',
    'Calibri',
    'Californian FB',
    'Calisto MT',
    'Cambria',
    'Candal',
    'CAPTURE IT',
    'Carbon Type',
    'Carrington',
    'Caveat',
    'Caviar dreams',
    'Century Schoolbook',
    'Chango',
    'Charmonman',
    'Chewy',
    'Chilanka',
    'Chiller',
    'Chomsky',
    'ChunkFive',
    'CINZEL',
    'CINZEL DECORATIVE',
    'Coiny',
    'Colonna MT',
    'Comfortaa',
    'Comic Sans MS',
    'Concert One',
    'Cookie',
    'Cormorant Unicase',
    'COSTURA LIGHT',
    'Courier New',
    'Crass Roots',
    'CREEPSTER',
    'Croissant One',
    'Cutive Mono',
    'Dancing Script',
    'Darker Script',
    'Darker Grotesque',
    'Deutsch Gothic',
    'Didact Gothic',
    'DIGNA\'S HANDWRITING',
    'Domine',
    'Dosis',
    'Economica',
    'Eczar SemiBold',
    'EDO',
    'Elsie Swash Caps',
    'Emblema One',
    'Englebert',
    'Euphoria Script',
    'Exo',
    'Exo 2',
    'Fahkwang',
    'Fjalla One',
    'Franklin Gothic',
    'Fredericka the Great',
    'Fredoka One',
    'Free Universal',
    'FRENTHE H1',
    'Fugaz One'
]